// Simulates an OS-level Outlook notification (not a website popup) so it's
// visually clear the OTP is "delivered by email", not generated by the site.
// The mail icon below is an original simple drawing — not Microsoft's logo —
// used only to suggest "an email client" for this demo.

export default function OutlookOtpToast({ email, code, onClose }) {
  return (
    <div
      className="fixed top-4 right-4 z-50 w-80 rounded-lg shadow-2xl border overflow-hidden animate-[slideIn_0.3s_ease-out]"
      style={{ background: "#F3F2F1", borderColor: "#D1D1D1" }}
      role="alert"
    >
      <style>{`
        @keyframes slideIn {
          from { transform: translateX(120%); opacity: 0; }
          to { transform: translateX(0); opacity: 1; }
        }
      `}</style>

      <div className="flex items-start gap-3 p-3" style={{ background: "#FFFFFF" }}>
        {/* generic mail icon, not Microsoft's logo */}
        <div
          className="w-9 h-9 rounded-md flex items-center justify-center shrink-0"
          style={{ background: "#0A66C2" }}
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
            <rect x="2" y="4" width="20" height="16" rx="2" stroke="white" strokeWidth="2" />
            <path d="M3 6l9 7 9-7" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between">
            <p className="text-xs font-semibold" style={{ color: "#242424" }}>Outlook</p>
            <button
              onClick={onClose}
              className="text-xs leading-none px-1"
              style={{ color: "#605E5C" }}
              aria-label="Dismiss notification"
            >
              ✕
            </button>
          </div>
          <p className="text-xs mt-0.5" style={{ color: "#242424" }}>
            New message — Verify your HTU account
          </p>
          <p className="text-xs mt-1 truncate" style={{ color: "#605E5C" }}>
            To: {email}
          </p>
          <p className="text-sm font-semibold mt-2 tracking-wide" style={{ color: "#0A66C2" }}>
            Your verification code: {code}
          </p>
        </div>
      </div>
    </div>
  );
}
